language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libsdl1.2-dev

sudo: false

compiler:
  - gcc
  - clang

before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update > /dev/null && brew install sdl; fi'

script:
  - make
  - 'make check'
